{
 "title": "Block Indexer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "chain", "query": { "query": "label_values(chain)" } }
  ]
 },
 "panels": [
  { "title": "Block Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current/Last Fetched Block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockchain_indexer_blockproducer_current_node_block{chain=\"$chain\"}",
     "legendFormat": "current_block_{{chain}}"
    },
    {
     "expr": "blockchain_indexer_blockproducer_last_fetched_block{chain=\"$chain\"}",
     "legendFormat": "last_fetched_block_{{chain}}"
    }
   ]
  },
  {
   "title": "Kafka Message Size (In Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "blockchain_indexer_blockproducer_kafka_message_size_bytes{chain=\"$chain\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Last Fetched Block",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_indexer_blockproducer_last_fetched_block{chain=\"$chain\"}",
     "legendFormat": "current_block_{{chain}}"
    }
   ]
  },
  {
   "title": "Node Current Block",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_indexer_blockproducer_current_node_block{chain=\"$chain\"}",
     "legendFormat": "current_block_{{chain}}"
    }
   ]
  },
  {
   "title": "Block Lag",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_indexer_blockproducer_current_node_block{chain=\"$chain\"}-blockchain_indexer_blockproducer_last_fetched_block{chain=\"$chain\"}",
     "legendFormat": "current_block_{{chain}}"
    }
   ]
  },
  { "title": "Block Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Offset by Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "blockchain_indexer_blockconsumer_topic_partition_offset{chain=\"$chain\"}",
     "legendFormat": "{{chain}}__{{topic}}__{{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "blockchain_indexer_blockconsumer_topic_lag{chain=\"$chain\"}",
     "legendFormat": "{{chain}}__{{topic}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "HTTP Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(blockchain_indexer_api_http_requests_total{}[$__rate_interval])) by (path)",
     "legendFormat": "{{instance}}{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Response Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(blockchain_indexer_api_http_response_status[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Node Current Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "blockchain_indexer_nodes_node_current_block{chain=\"$chain\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "blockchain_indexer_nodes_node_latency{chain=\"$chain\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "blockchain_indexer_nodes_node_status{chain=\"$chain\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}