global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    static_configs:
      - targets: ['pushgateway:9091', 'localhost:9091']

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8420']
